In [1]:
import pandas as pd
import geopandas as gpd
import os
import numpy as np

from future_land_use.util.pipeline import Pipeline
from future_land_use.util.clean_unique_ids import clean_id

p = Pipeline('configs')

In [10]:
prcl = p.get_table('parcels_land_use_type')
flu = p.get_table('flu_imputed_hb_1110_with_overlays').drop(columns=['juris_zn','hb_1110_tier'])

In [12]:
df = p.get_table('parcel_plan_type_xwalk_with_overlays_hb_1110')
# df = df.merge(prcl, on='parcel_id', how='left')
df = df.merge(flu, on='plan_type_id', how='left')

In [ ]:
today = pd.Timestamp.today().strftime('%Y-%m-%d')
df.to_csv(f'output/parcel_flu_join_{today}.csv', index=False)

In [28]:
king = df.loc[df['Juris'] == 'King_County'].copy()
king['acres'] = king['gross_sqft'] / 43560

In [29]:
king.columns

Index(['parcel_id', 'juris_zn', 'plan_type_id', 'hb_1110_tier_x', 'lu_type',
       'tod_id', 'gross_sqft', 'FLU_master_id', 'Juris', 'Bonus_included',
       'Res_Use', 'Comm_Use', 'Office_Use', 'Indust_Use', 'Mixed_Use',
       'FloorMaxDU_lot', 'MinDU_Res', 'MinFAR_Comm', 'MinFAR_Office',
       'MinFAR_Indust', 'MinFAR_Mixed', 'MaxDU_Res', 'MaxFAR_Comm',
       'MaxFAR_Office', 'MaxFAR_Indust', 'MaxFAR_Mixed', 'MaxHt_Res',
       'MaxHt_Comm', 'MaxHt_Office', 'MaxHt_Indust', 'MaxHt_Mixed', 'LC_Res',
       'LC_Comm', 'LC_Office', 'LC_Indust', 'LC_Mixed', 'rural',
       'SingleFamily_Use', 'MultiFamily_Use', 'MinDU_lot', 'MinDU_Mixed',
       'Notes', 'MaxDU_Mixed', 'city_name', 'hb_1110_tier_y',
       'hb_transit_override', 'overlay_combo_id', 'acres'],
      dtype='str')

In [30]:
res_king = king.loc[king['Res_Use'] == 1].copy()

In [31]:
res_king['du_capacity'] = res_king['acres'] * res_king['MaxDU_Res']

In [32]:
res_king.groupby('juris_zn').agg({'acres':'sum','du_capacity':'sum','parcel_id':'count'}).round(0).astype(int).sort_values(by='du_capacity', ascending=False).rename(columns={'parcel_id':'parcel_count'})

                     acres  du_capacity  parcel_count
juris_zn
King_County_R-6       5538        99690         19689
King_County_R-4       6195        74337         12202
King_County_RA-5    123762        24752         38192
King_County_R-18       434        23454          1095
King_County_R-24       325        23382           394
King_County_R-12       409        14740          1331
King_County_R-48        91        13033           112
King_County_F       815532        10194          4642
King_County_R-8        410         9829           882
King_County_R-1       4846         7269          1083
King_County_RA-2.5   17270         6908         12150
King_County_RA-10    49668         4967          5421
King_County_NB         185         4447           242
King_County_UR        2147         3221          1054
King_County_CB         389         1556           577
King_County_A-10     12800         1280          1476
King_County_A-35     28130          805          2116
King_County_RB           4          507            12
King_County_O           72          288            46

In [33]:
res_king['du_capacity'].sum()

np.float64(324657.07911706064)

In [24]:
res_king['du_capacity'].sum()

np.float64(489420.82991617714)

In [10]:
res_king['du_capacity'].sum()

np.float64(2369158.031067256)

In [11]:
df

,parcel_id,juris_zn,plan_type_id,hb_1110_tier_x,lu_type,tod_id,gross_sqft,FLU_master_id,Juris,Bonus_included,...,SingleFamily_Use,MultiFamily_Use,MinDU_lot,MinDU_Mixed,Notes,MaxDU_Mixed,city_name,hb_1110_tier_y,hb_transit_override,overlay_combo_id
0,1,Kent_I3,608.0,1.0,22,0,367587.106028,589.0,Kent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Kent,1.0,NaN,NaN
1,2,Kent_I1,606.0,1.0,26,0,5453.828488,587.0,Kent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Kent,1.0,NaN,NaN
2,3,Kent_I1,606.0,1.0,18,0,6000.066365,587.0,Kent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Kent,1.0,NaN,NaN
3,4,Kent_I1,606.0,1.0,18,0,7200.084044,587.0,Kent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Kent,1.0,NaN,NaN
4,5,Kent_I1,606.0,1.0,26,0,6068.041674,587.0,Kent,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Kent,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1329922,1009455,Pierce_County_SR,1145.0,NaN,25,0,88319.000000,1119.0,Pierce_County,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329923,1009456,Pierce_County_SR,1145.0,NaN,17,0,182440.000000,1119.0,Pierce_County,Y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329924,1024947,Gig_Harbor_R-1,506.0,NaN,22,0,2053.000000,480.0,Gig_Harbor,NaN,...,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1329925,1213763,Arlington_RLC,30.0,3.0,24,0,6460.491723,30.0,Arlington,Y,...,Y,NaN,NaN,NaN,NaN,NaN,Arlington,3.0,NaN,NaN
1329926,1329378,Brier_RS_12500,234.0,3.0,17,0,420.597936,211.0,Brier,NaN,...,Y,Y,NaN,NaN,NaN,NaN,Brier,3.0,NaN,NaN

In [12]:
cfg = p.settings['hb1110_settings']
p.get_onedrive_path(cfg['transit_gdb_path']), cfg['transit_walksheds_layer']

(WindowsPath('C:/Users/JKolberg/OneDrive - PSRC/GIS - Sharing/Projects/FLU/transit_hb_1110.gdb'),
 'hb_1110_walksheds')

In [13]:
gpd.read_file(p.get_onedrive_path(cfg['transit_gdb_path']), layer=cfg['transit_walksheds_layer'])

c:\Users\jkolberg\PythonProjects\PSRC\future_land_use\.venv\Lib\site-packages\pyogrio\raw.py:200: RuntimeWarning: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
  return ogr_read(

,Shape_Length,Shape_Area,geometry
0,2.314942e+06,8.400560e+08,"MULTIPOLYGON (((1227061.262 60787.138, 1227028..."

In [14]:
def load_overlay_layers(gdb_path, layers):
    gdf_out = gpd.GeoDataFrame()
    for layer in layers:
        # grab each layer from the geodatabase and create a juris_zn column if it doesn't exist
        gdf = gpd.read_file(gdb_path, layer=layer['layer'])
        gdf = gdf.to_crs(epsg=2285)
        if 'juris_zn_col' not in layer:
            gdf['juris_zn'] = layer['juris'] + '_' +  gdf[layer['zone_col']]
        elif 'zone_col' not in layer:
            gdf = gdf.rename(columns={layer['juris_zn_col']: 'juris_zn'})
        else:
            raise ValueError(f"Layer {layer['layer']} must have either 'juris_zn_col' or 'zone_col' specified in settings.yaml")
        gdf['juris'] = layer['juris']
        # remove any non-alphanumeric characters from the juris_zn column
        gdf['juris_zn'] = gdf['juris_zn'].apply(clean_id)
        gdf = gdf.dissolve(by='juris_zn', as_index=False)
        gdf_out = pd.concat([gdf_out, gdf[['juris','juris_zn', 'geometry']]], ignore_index=True)
    return gdf_out

In [15]:
p = Pipeline('configs')
global_cfg = p.settings
cfg = p.settings.get('overlay_settings', {})
input_overlay_gdb = p.get_onedrive_path(cfg.get('overlay_gdb_path', ''))

# load flu table
flu_table_path = p.get_onedrive_path(cfg.get('flu_table_path', ''))
flu_juris_zn_col = cfg.get('flu_juris_zn_col', '')
df = pd.read_excel(flu_table_path)
df['juris_zn'] = df[flu_juris_zn_col]

# load overlay gis layers
gdf = load_overlay_layers(input_overlay_gdb, cfg.get('overlay_layers', []))

flu_table_path = p.get_onedrive_path(cfg.get('flu_table_path', ''))
flu_juris_zn_col = cfg.get('flu_juris_zn_col', '')
df = pd.read_excel(flu_table_path)
df['juris_zn'] = df[flu_juris_zn_col]

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\JKolberg\\OneDrive - PSRC\\GIS - Sharing\\Projects\\FLU\\Zoning_2026_d3.xlsx'

In [ ]:
df

,Juris,Zone,juris_zn,Definition,Bonus_avail,Bonus_included,Res_Use,Comm_Use,Office_Use,Indust_Use,...,LC_Office,LC_Indust,LC_Mixed,rural,ADU notes,Unnamed: 0,Unnamed: 47,Unnamed: 48,Unnamed: 49,Notes
0,Algona,C-1,Algona_C-1,The C-1 mixed use commercial district is inten...,Y,NaN,Y,Y,Y,NaN,...,NaN,NaN,75,NaN,"Up to two ADUs permitted per lot, do not count...",NaN,NaN,NaN,NaN,NaN
1,Algona,C-1,Algona_C-1,The C-1 mixed use commercial district is inten...,Y,Y,Y,Y,Y,NaN,...,NaN,NaN,75,NaN,"Up to two ADUs permitted per lot, do not count...",NaN,NaN,NaN,NaN,NaN
2,Algona,C-2,Algona_C-2,The C-2 general commercial district is intende...,Y,NaN,Y,Y,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Algona,C-2,Algona_C-2,The C-2 general commercial district is intende...,Y,Y,Y,Y,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Algona,C-3,Algona_C-3,The C-3 heavy commercial district is intended ...,Y,NaN,Y,Y,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2431,Woodway,R-87,Woodway_R-87,The primary function of the residential R-87 z...,NaN,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2432,Woodway,UR,Woodway_UR,The primary purpose of the UR zone district is...,NaN,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2433,Woodway,UV,Woodway_UV,The purpose of the urban village (UV) zone is ...,NaN,NaN,Y,Y,Y,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2434,Yarrow_Point,R-12,Yarrow_Point_R-12,The purpose of this title is to regulate the u...,NaN,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2435,Yarrow_Point,R-15,Yarrow_Point_R-15,The purpose of this title is to regulate the u...,NaN,NaN,Y,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data_dir = p.get_data_path()

manual_match_path = os.path.join(data_dir, 'overlay_manual_match.csv')
if os.path.exists(manual_match_path):
    print("loading existing manual match file")
    manual_match_df = pd.read_csv(manual_match_path)
    # save backup of the existing manual match file with a timestamp
    backup_path = os.path.join(data_dir, f"overlay_manual_match_backup_{pd.Timestamp.now().strftime('%Y%m%d_%H%M%S')}.csv")
    manual_match_df.to_csv(backup_path, index=False)
    # create a mapping of juris_zn to juris_zn_manual_match and apply it to the gdf
    manual_match = manual_match_df.set_index('juris_zn')['juris_zn_manual_match']
    gdf['juris_zn_manual_match'] = gdf['juris_zn'].map(manual_match)
    # if there is a manual match, use it to update the juris_zn column in the gdf
    gdf['juris_zn'] = np.where(gdf['juris_zn_manual_match'].notnull(), gdf['juris_zn_manual_match'], gdf['juris_zn'])

# merge overlay layers with flu table, flag rows that don't have a match
gdf = gdf.merge(flu_table, on=['juris','juris_zn'], how='left')

,juris,juris_zn,geometry
0,University_Place,University_Place_CCPO,"MULTIPOLYGON (((1213928.838 76290.96, 1214048...."
1,University_Place,University_Place_DIO,"POLYGON ((1210883.218 91406.079, 1210816.701 9..."
2,University_Place,University_Place_DISSO,"MULTIPOLYGON (((1208000.331 83967.081, 1207834..."
3,Poulsbo,Poulsbo_MPO,"MULTIPOLYGON (((1194885.872 276373.205, 119496..."
4,Kitsap,Kitsap_Bucklin_Hill_Center,"POLYGON ((1181501.76 241919.819, 1181520.746 2..."
5,Kitsap,Kitsap_Clear_Creek_Village,"POLYGON ((1182373.757 243520.083, 1182850.384 ..."
6,Kitsap,Kitsap_Kitsap_Mall_Center,"POLYGON ((1180867.874 244172.032, 1180874.473 ..."
7,Kitsap,Kitsap_Northeast_Business_Park,"POLYGON ((1184180.991 244122.127, 1184336.016 ..."
8,Kitsap,Kitsap_Old_Town_Center_District,"POLYGON ((1180082.615 239183.324, 1180518.137 ..."
9,Kitsap,Kitsap_Provost_Commercial_District,"POLYGON ((1179673.576 245849.742, 1179456.514 ..."
10,Kitsap,Kitsap_Waaga_Way_Town_Center,"POLYGON ((1179720.36 250739.84, 1179847.522 25..."
11,Kitsap,Kitsap_Waterfront_District,"POLYGON ((1186356.131 244064.183, 1186371.688 ..."
12,Kitsap,Kitsap_West_Hill_Neighborhood,"POLYGON ((1179947.911 246039.762, 1180265.622 ..."
13,Tacoma,Tacoma_ACD,"POLYGON ((1230208.327 72145.347, 1230210.834 7..."
14,Tacoma,Tacoma_CONS,"MULTIPOLYGON (((1241515.949 92717.014, 1241518..."
15,Tacoma,Tacoma_HIST,"MULTIPOLYGON (((1241932.09 93135.381, 1241945...."
16,Tacoma,Tacoma_PRD,"MULTIPOLYGON (((1224915.229 78333.214, 1224809..."
17,Tacoma,Tacoma_PTD-A,"MULTIPOLYGON (((1261752.56 101246.942, 1262158..."
18,Tacoma,Tacoma_PTD-B,"POLYGON ((1261759.205 101563.438, 1262259.153 ..."
19,Tacoma,Tacoma_STGPD,"MULTIPOLYGON (((1226383.791 71862.542, 1226327..."
20,Tacoma,Tacoma_STMIC,"POLYGON ((1228940.917 75235.423, 1228941.608 7..."
21,Tacoma,Tacoma_VSD-20,"MULTIPOLYGON (((1216106.522 93205.582, 1215905..."
22,Tacoma,Tacoma_VSD-25,"MULTIPOLYGON (((1216254.587 92720.289, 1216181..."

In [ ]:
df.loc[df['hb_1110_tier'] > 0][['city_name','hb_1110_tier']].to_csv('output/hb_1110_tiers.csv', index=False)